config/routes.rb
Rails.application.routes.draw do
  resources :locations do
    resources :ratings
  end
  resources :users
  resources :sessions
  resources :times

  root 'locations#home'

  get 'index' => 'locations#home'
  get 'about' => 'locations#about'
  get 'register' => 'users#register'
  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'logout' => 'sessions#destroy'
  get 'destroy_time' => 'times#destroy'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :ratings


  def gmaps4rails_address
    address
  end

  #converts the rating to a string for referencing icons
  #in application.js for the google maps marker
  #by using average of ratings for location
  def convert()
    if self.ratings == nil
      'icons.unrated.icon'
    end
    total = self.ratings.map{|x| x}
    rating_array = []
    total.each do |x|
      rating_array << x.rating_score
    end
    average = rating_array.inject{ |sum, el| sum + el }.to_f / rating_array.size

    if average < 3.25
      'icons.bad.icon'
    elsif average < 4
      'icons.average.icon'
    elsif average <= 5
      'icons.great.icon'
    else
      'icons.unrated.icon'
    end
  end


end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :location

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :user_name, uniqueness: true
  validates :user_password, length: { minimum: 6 }
  validates :user_name, length: { minimum:  2}

  def self.authenticate(name, password)
    user = find_by(user_name: name)
    if user && user.user_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if user_password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.user_password= BCrypt::Engine.hash_secret(user_password, salt)
    end
  end

  def clear_password
    user_password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_time
  helper_method :user_date

  #private

  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id]) if session[:user_id]
  end

  def user_time
    @user_time = session[:user_time] if session[:user_time] != nil
  end

  def user_date
    @user_date = session[:user_date] if session[:user_date] != nil
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy, :rate]

  # GET /locations
  # GET /locations.json
  def home
    @locations = Location.all

    @days = [[0, 'sunday'], [1, 'monday'], [2, 'tuesday'], [3, 'wednesday'],
    [4, 'thursday'], [5, 'friday'], [6, 'saturday']]

    @time = Time.new
  end

  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new

    @days = [@sunday, @monday, @tuesday, @wednesday, @thursday, @friday, @saturday]
    @days.each do |this|
      this = false
    end

  end
  #
  # def rate_index
  #   @locations = Location.all
  # end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @temp = Geocoder.search(@location.address)
    @location.latitude = @temp[0].latitude
    @location.longitude = @temp[0].longitude

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|

      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :address, :longitude, :latitude, :gmaps, :hstart, :hend, :hmenu, :hrating, :number, :days, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :hrating, :hcounter)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]


  def new
    @rating = Rating.new
    @location = Location.find(params[:location_id])
  end

  def edit
    @location = Location.find(params[:location_id])
  end

  def create
    @rating = Rating.new(user_params)
    @rating.location_id = Location.find(params[:location_id]).id
    @rating.user_name = current_user.user_name
    if @rating.save
      flash[:notice] = 'Successful Rating'
      redirect_to index_path
    else
      flash[:notice] = 'Unsuccessful Rating'
      redirect_to index_path
    end
  end

  def update
    if @rating.update(user_params)
      flash[:notice] = 'Rating was changed.'
      redirect_to index_path
    else
      flash[:notice] = 'Unsuccessful Rating'
      redirect_to index_path
    end
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def user_params
    params.require(:rating).permit(:rating_score)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  # "Create" a login, aka "log the user in"
  def create
    user = User.authenticate(params[:user_name], params[:user_password])
    if user
      session[:user_id] = user.id
      redirect_to index_path, :notice => "Logged in!"
    else
      flash[:notice] =  'Login unsuccessful.'
      redirect_to log_in_path
    end
  end

  # "Delete" a login, aka "log the user out"
  def destroy
    # Remove the user id from the session
    flash[:notice] = "You have successfully logged out."
    session[:user_id] = nil
    redirect_to destroy_time_path
  end

end

app/controllers/times_controller.rb
class TimesController < ApplicationController

  def new

  end

  def create
    # user = current_user
    #
    # session[:time] = Time.now
    session[:user_time] = params[:user_time]
    session[:user_date] = params[:day]
    redirect_to root_url

  end

  def destroy
    # time[:user_id] = nil
    session[:user_time] = nil
    session[:user_date] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def register
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.encrypt_password
    if @user.save
      flash[:notice] = 'User was successfully created.'
      redirect_to index_path
    else
      render 'register'
    end

    @user.clear_password

  end

  def user_params
    params.require(:user).permit(:user_name, :user_password)
  end

  def username_param
    params.require(:user).permit(:user_name)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @days = [[0, 'sunday'], [1, 'monday'], [2, 'tuesday'], [3, 'wednesday'],
            [4, 'thursday'], [5, 'friday'], [6, 'saturday']]

    @time = Time.new

    

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyHour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">

      <a class="navbar-brand" href="/index">Happy Hours</a>
      </div>
      <form class="navbar-form navbar-right">
        <% if current_user %>
          <strong>Logged in as: </strong> <%= current_user.user_name %>
          <a class="btn btn-danger" <%= link_to 'Log out', logout_path %></button>
        <% else %>
          <a class="btn btn-success" <%= link_to 'Log in', log_in_path %></button>
          <a class="btn btn-primary" <%= link_to 'Sign up', register_path %></button>
        <% end %>
      </form>
    </div>
  </div>
  <div class="container">
    <%= yield %>

    <footer>
      <div class="row">
        <div class= "col-md-6">
          <%= link_to "Home", root_path %>
          |
          <%= link_to "About", about_path %>
          |
          <%= link_to "Bars", locations_path %>
        </div>

        <div class="col-md-6 text-right">
          <a href="https://www.linkedin.com/in/danielwharrisdenver">
            <%= image_tag 'linkedin.png', class: "img-footer", alt: "LinkedIn" %>
          </a>
          <a href="https://github.com/DaHarris">
            <%= image_tag 'github.png', class: "img-footer", alt: "Github" %>
          </a>
          <a href="https://twitter.com/bobth3bum">
            <%= image_tag 'twitter.png', class: "img-footer", alt: "Twitter" %>
          </a>
          <a href="https://students.gschool.it/students/201">
            <%= image_tag 'galvanize.png', class: "img-footer", alt: "Galvanize" %>
          </a>
        </div>
      </div>
    </footer>
  </div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-horizontal">
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label :name %><br></div>
      <div class="form-ctonrols col-md-4"><%= f.text_field :name %></div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label :address %><br></div>
      <div class="form-ctonrols col-md-4"><%= f.text_field :address %></div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label 'HappyHour start' %><br></div>
      <div class="form-ctonrols col-md-4"><%= f.time_field :hstart %></div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label 'HappyHour end' %><br></div>
      <div class="form-ctonrols col-md-4"><%= f.time_field :hend %></div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label 'HappyHour Menu' %><br></div>
      <div class="form-controls col-md-4"><%= f.text_area :hmenu, :cols => "50", :rows => "10" %></div>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <div class="control-label col-md-2"><%= f.label 'Days of the Week' %><br></div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:sunday) %> Sunday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:monday) %> Monday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:tuesday) %> Tuesday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:wednesday) %> Wednesday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:thursday) %> Thursday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:friday) %> Friday
        </div>
      </div>
      <div class="col-md-1">
        <div class="checkbox">
          <%= f.check_box(:saturday) %> Saturday
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <% if @location.name == nil %>
      <input class="btn btn-primary" name="commit" type="submit" value="Create Location">
      <% else %>
      <input class="btn btn-primary" name="commit" type="submit" value="Update Location">
      <% end %>
      <a class="btn btn-default" <%= link_to 'Cancel', locations_path %>
      </div>
    </div>
</div>

  <!-- #removed fields
  <div class="field">
  <%= f.label :gmaps %><br>
  <%= f.check_box :gmaps %>
  </div>
  <div class="field">
  <%= f.label :hmenu %><br>
  <%= f.text_field :hmenu %>
  </div>
  <div class="field">
  <%= f.label :hrating %><br>
  <%= f.text_field :hrating %>
  </div>
  <div class="field">
  <%= f.label :number %><br>
  <%= f.text_field :number %>
  </div>  -->


<% end %>

app/views/locations/about.html.erb
<div class="page-header">
  <h1>About HappyHour</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <p> HappyHour is a tool used to find your (soon) favorite bars and nightclubs
      in your area. We do this with two colored spheres over all of the bars
      in our database for your area. The colors go from Green:(good) to Red:(you knew it
      you clever human, bad). These two spheres represent these values:
    </p>
    <br>
    <ul>
      <li><strong>Left sphere:</strong> Time left for the location's HappyHour</li>
      <li><strong>Right sphere:</strong> The average rating of the HappyHour by our users</li>
    </ul>
    <br>
    <p> We hope you find some new awesome places! Check back soon for even more functionality.
      In the meantime, drink up (but always take a cab home plz)
    </p>
  </div>
</div>

app/views/locations/edit.html.erb
<div class="page-header">
  <h1>Editing Location</h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Locations", locations_path %></li>
  <li><%= link_to "#{@location.name}", @location %></li>
  <li class="active">New Location</li>
</ul>

<%= render 'form' %>

app/views/locations/home.html.erb
<% if notice != nil %>
<p id="notice">
  <div class="alert alert-success text-centered" role="alert">
    <p class="text-center"><%= notice %></p>
  </div>
</p>
<% end %>

<% if current_user %>
  <%= render :partial => 'times/form' %>
<% end %>

<hr>
<div class="row">
  <div class="form-group">
    <div class="col-md-12">
      <div id="map" style='height:500px;'>
        <script type="text/javascript">
          mapBuilder();
        </script>
        <% if @locations != nil %>
          <% @locations.each do |each_location| %>
            <% converted_ratings = each_location.convert %>
            <% converted_start = each_location.hstart.strftime("%H:%M") %>
            <% converted_end = each_location.hend.strftime("%H:%M") %>
            <% if user_time %>
              <% if user_time > each_location.hstart.strftime("%H:%M") && user_time < each_location.hend.strftime("%H:%M") %>
                <% if each_location.send(user_date) %>
                  <script type="text/javascript">
                    placeMarker(<%= each_location.latitude %>, <%=each_location.longitude %>, "<%= each_location.name %>",
                              "<%=converted_start%>", "<%=converted_end%>", "<%=converted_ratings%>", "<%=each_location.hmenu%>");
                  </script>
                <% end %>
              <% end %>
            <% else %>
              <script type="text/javascript">
                placeMarker(<%= each_location.latitude %>, <%=each_location.longitude %>, "<%= each_location.name %>",
                          "<%=converted_start%>", "<%=converted_end%>", "<%=converted_ratings%>", "<%=each_location.hmenu%>");
              </script>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- <div class="col-md-4">
      <h3 align="center"> Popular locations </h3>
      <button type="button" class="btn btn-info btn-block"><%= 'Downtown' %></button>
      <br>
      <button type="button" class="btn btn-info btn-block"><%= 'South Broadway' %></button>
      <br>
      <button type="button" class="btn btn-info btn-block"><%= 'Highlands' %></button>
    </div> -->
  </div>
</div>

app/views/locations/index.html.erb
<% if notice != nil %>
<p id="notice">
  <div class="alert alert-danger text-centered" role="alert">
    <p class="text-center"><%= notice %></p>
  </div>
</p>
<% end %>

<div class="page-header">
  <div class="pull-right">
    <a class="btn btn-primary" <%= link_to 'New Location', new_location_path %></a>
  </div>
  <h1>Locations</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Names:</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to "#{location.name}", location %></td>
        <td class="text-right">
          <% if current_user && location.ratings.find_by_user_name(current_user.user_name) %>
            <a class="btn btn-info" <%= link_to 'Edit Rating', edit_location_rating_path(location, location.ratings.find_by_user_name(current_user.user_name)) %>
          <% elsif current_user %>
            <a class="btn btn-info" <%= link_to 'Rate', new_location_rating_path(location) %>
          <% end %>
          <a class="btn btn-success" <%= link_to 'Edit', edit_location_path(location) %>
          <a class="btn btn-danger" <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/locations/new.html.erb
<div class="page-header">
  <h1>New Location</h1>
</div>


<ul class="breadcrumb">
  <li><%= link_to "Locations", locations_path %></li>
  <li class="active">New Location</li>
</ul>

<%= render 'form' %>

app/views/locations/rate.html.erb
<!-- # <%= form_for(@rating) do |f| %>
#   <% if @rating.errors.any? %>
#     <div id="error_explanation">
#       <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this location from being saved:</h2>
#
#       <ul>
#         <% @rating.errors.full_messages.each do |message| %>
#         <li><%= message %></li>
#         <% end %>
#       </ul>
#     </div>
#   <% end %>
#   <div class="form-horizontal">
#     <div class="form-group">
#       <div class="field">
#         <div class="control-label col-md-2"><%= f.label 'HappyHour Rating' %><br></div>
#         <div class="form-controls col-md-4"><%= f.number_field :rating_score, :min => '1', :max => '5', :class => 'text_field', :step => 0.5 %></div>
#       </div>
#     </div>
#     <div class="form-group">
#       <div class="col-md-offset-2 col-md-4">
#         <input class="btn btn-primary" name="commit" type="submit" value="Rate Location">
#         <a class="btn btn-default" <%= link_to 'Cancel', locations_path %>
#       </div>
#     </div>
#   </div>
# <% end %> -->

app/views/locations/rate_index.html.erb
<!-- <link href="path/to/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="path/to/js/star-rating.min.js" type="text/javascript"></script>

<% if notice != nil %>
<p id="notice">
  <div class="alert alert-success text-centered" role="alert">
    <p class="text-center"><%= notice %></p>
  </div>
</p>
<% end %>

<div class="page-header">
  <h1>Locations</h1>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Names:</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to "#{location.name}", location %></td>
        <td class="text-right">
          <a class="btn btn-info" <%= link_to 'Rate', rate_location_path(location) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br> -->

app/views/locations/show.html.erb
<% if notice != nil %>
<p id="notice">
  <div class="alert alert-success text-centered" role="alert">
    <p class="text-center"><%= notice %></p>
  </div>
</p>
<% end %>

<ul class="breadcrumb">
  <li><%= link_to "Locations", locations_path %></li>
  <li><%= link_to "#{@location.name}", @location %></li>
  <li class="active">New Location</li>
</ul>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Hstart:</strong>
  <%= @location.hstart.strftime("%H:%M") %>
</p>

<p>
  <strong>Hend:</strong>
  <%= @location.hend.strftime("%H:%M") %>
</p>

<p>
  <strong>Hmenu:</strong>
  <%= @location.hmenu %>
</p>


<p>
  <strong>Ratings:</strong>
  <% @location.ratings.each do |x| %>
    <%= x.rating_score %>
  <% end %>
</p>


<p>
    <a class="btn btn-primary" <%= link_to 'Go Back', locations_path %>
</p>

app/views/ratings/edit.html.erb
<%= form_for([@location, @rating]) do |f| %>
<% if @rating.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this location from being saved:</h2>

  <ul>
    <% @rating.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-horizontal">
  <div class="form-group">
    <div class="field">
      <% if @location.ratings.find_by_user_name(current_user.user_name) %>
      <div class="control-label col-md-2"><%= f.label 'HappyHour Rating' %><br></div>
      <div class="form-controls col-md-4"><%= f.number_field :rating_score, :min => '1', :max => '5', :class => 'text_field', :step => 0.5, :value => @location.ratings.find_by_user_name(current_user.user_name).rating_score %></div>
      <% else %>
      <div class="control-label col-md-2"><%= f.label 'HappyHour Rating' %><br></div>
      <div class="form-controls col-md-4"><%= f.number_field :rating_score, :min => '1', :max => '5', :class => 'text_field', :step => 0.5 %></div>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <% if @location.ratings.find_by_user_name(current_user.user_name) %>
      <input class="btn btn-primary" name="commit" type="submit" value="Update location rating">
      <% else %>
      <input class="btn btn-primary" name="commit" type="submit" value="Create rating">
      <% end %>
      <a class="btn btn-default" <%= link_to 'Cancel', locations_path %>
      </div>
    </div>
  </div>
  <% end %>

app/views/ratings/new.html.erb
<%= form_for([:location, @rating]) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% @rating.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-horizontal">
    <div class="form-group">
      <div class="field">
        <% if @location.ratings.find_by_user_name(current_user.user_name) %>
          <div class="control-label col-md-2"><%= f.label 'HappyHour Rating' %><br></div>
          <div class="form-controls col-md-4"><%= f.number_field :rating_score, :min => '1', :max => '5', :class => 'text_field', :step => 0.5, :value => @location.ratings.find_by_user_name(current_user.user_name).rating_score %></div>
        <% else %>
          <div class="control-label col-md-2"><%= f.label 'HappyHour Rating' %><br></div>
          <div class="form-controls col-md-4"><%= f.number_field :rating_score, :min => '1', :max => '5', :class => 'text_field', :step => 0.5 %></div>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-4">
        <% if @location.ratings.find_by_user_name(current_user.user_name) %>
          <input class="btn btn-primary" name="commit" type="submit" value="Update location rating">
        <% else %>
          <input class="btn btn-primary" name="commit" type="submit" value="Create rating">
        <% end %>
        <a class="btn btn-default" <%= link_to 'Cancel', locations_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/times/_form.html.erb
<%= form_tag times_path do %>
  <div class="form-horizontal">
    <div class="form-group">
      <div class="field">
        <div class="col-md-1"></div>
        <% if user_time %>
          <%= label_tag 'When are you going out?'%>
          <%= time_field_tag :user_time, (user_time or Time.now.strftime("%H%M")) %>
        <% else %>
          <%= label_tag 'When are you going out?' %>
          <%= time_field_tag :user_time, ("#{Time.now.strftime("%H:%M")}") %>
        <% end %>
        <% ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'].each do |dow| %>
          <% if user_date == dow %>
            <%= label_tag dow %>
            <%= radio_button_tag(:day, dow, checked = true) %>
          <% elsif !user_date && Time.now.strftime("%A") == dow %>
            <%= label_tag dow %>
            <%= radio_button_tag(:day, dow, checked = true) %>
          <% else %>
            <%= label_tag dow %>
            <%= radio_button_tag(:day, dow) %>
          <% end %>
        <% end %>
        <%= submit_tag %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/register.html.erb
<% if notice != nil %>
<p id="notice">
  <div class="alert alert-danger text-centered" role="alert">
    <p class="text-center"><%= notice %></p>
  </div>
</p>
<% end %>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this location from being saved:</h2>

    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <div class="page-header">
    <h1>Register</h1>
  </div>
  <div class="form-horizontal">
    <div class="form-group">
      <div class="field">
        <div class="control-label col-md-2"><%= f.label 'User Name' %><br></div>
        <div class="form-ctonrols col-md-4"><%= f.text_field :user_name %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="field">
        <div class="control-label col-md-2"><%= f.label 'Password' %><br></div>
        <div class="form-ctonrols col-md-4"><%= f.password_field :user_password %></div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-4">
        <input class="btn btn-primary" name="commit" type="submit" value="Create User">
        <a class="btn btn-default" <%= link_to 'Cancel', index_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/welcome/about.html.erb
<div class="page-header">
  <h1>About HappyHour</h1>
</div>

<div class="row">
  <div class="col-md-6">
    <p> HappyHour is a tool used to find your (soon) favorite bars and nightclubs
      in your area. We do this with two colored spheres over all of the bars
      in our database for your area. The colors go from Green:(good) to Red:(you knew it
      you clever human, bad). These two spheres represent these values:
    </p>
    <br>
    <ul>
      <li><strong>Left sphere:</strong> Time left for the location's HappyHour</li>
      <li><strong>Right sphere:</strong> The average rating of the HappyHour by our users</li>
    </ul>
    <br>
    <p> We hope you find some new awesome places! Check back soon for even more functionality.
      In the meantime, drink up (but always take a cab home plz)
    </p>
  </div>
</div>